### ISSUE TITLE
Is this package maintained? 

### ISSUE THREAD

**Issue by patrickwall57** [koblas/sops-decoder-node#1]
This package has some great features - wondering if there is a maintainer willing to accept pull request/issues

**Comment by koblas** [comment]
yes

**Comment by patrickwall57** [comment]
Thats great! We are interested in using the encrypted-regex option with sops. Looking at the code for this module, its using a default value of the unencrypted_suffix. 

Is this an extension you would be interested in? Have you looked at this in the past and uncovered any challenges worth noting?

**Comment by koblas** [comment]
It would be a great addition, would love to see a PR to add it.

Plus, look at the lack of update in 3 years... thinking it's time to update my packages.

**Comment by koblas** [comment]
Patrick,

Thanks again.  Just a note, I've also now moved `master` => `main` for branching and builds to GitHub.  

Please give your changes a try with everything and let me know.

Also, while outside of the scope of your fix while I was poking around noticed that SOPS now supports Azure and GCP, wondering if it would be worthwhile to move to a more virtual key provider so this package can plug for all providers.

**Comment by patrickwall57** [comment]
Hey sorry for the late reply - everything is working great on our side with the new changes. I think its a good idea to support other cloud providers - we are an aws shop so i dont have a lot of experience with Azure/GCP.

Im really suprised there arent more community supplied issues asking about it. It seems like your getting pretty good downloads and that there would be interest from users of the other cloud providers
