### ISSUE TITLE
Hash mismatch when decoding nested _unencrypted branches

### ISSUE THREAD

**Issue by chris-grabcad** [koblas/sops-decoder-node#10]
Hi thanks for providing this package it was just what I was looking for, I have hit a small snag with nested _unencrypted branches in my json files, as follows.

I have a config file a little like this: -

```json
{
   "_unencrypted": {
       "key1": "plain text",
       "key2": "more plain text"
   },
  "SECRET1": "ENC[AES256_GCM...]",
  "sops" : {
      "kms": [...],
      ...
      "unencrypted_suffix": "_unencrypted"
}
```

The problem I'm having using sops-decoder is that when I decrypt this file I get an error "Hash mismatch" - thrown from [here](https://github.com/koblas/sops-decoder-node/blob/main/src/decode.ts#L106).

I did some tracking down and managed to identify that the issue was in walkAndDecrypt 

when it gets to "_unencrypted" in the input data it calls `doValue` with `unencrypted_branch = true`, however it then recursively calls `walkAndDecrypt` with `unencrypted = false`, so it treats the rest of the values as if they are encrypted.  I tried patching my package with patch-package and managed to get it working, I made this change

```ts
function walkAndDecrypt(
  tree: EncodedTree,
  key: Buffer,
  aad = "",
  digest: crypto.Hash,
  isRoot = true,
  unencrypted = false,
  encryptionModifier: EncryptionModifier,
): any {
  const doValue = (
    value: any,
    caad: string,
    unencrypted_branch: boolean,
  ): any => {
    if (Array.isArray(value)) {
      return value.map((vv) => doValue(vv, caad, unencrypted_branch));
    }
    if (typeof value === "object") {
      return walkAndDecrypt(
        value,
        key,
        caad,
        digest,
        false,
        unencrypted_branch,                                             // was false  <<<<<<<<< CHANGE HERE
        encryptionModifier,
      );
    }
    return decryptScalar(value, key, caad, digest, unencrypted_branch);
  };
```

**Comment by koblas** [comment]
Good catch.  Would you mind creating a pull request?

**Comment by chris-grabcad** [comment]
Done :-)

**Comment by koblas** [comment]
Merged.

I also updated the release process and updated the dependancies.  

Let me know if it's working for you
